### ISSUE TITLE
NMM: Get Mod Updates not working

### ISSUE THREAD

**Issue by InsaneVRGamer** [Nexus-Mods/Nexus-Mod-Manager#1345]
So my NMM was working fine using it for years, only thing ever use.. And all of a sudden i can't get mod updates by clicking the button that gets missing information and gets mod updates.

I have hundreds of mods downloaded.. and when i click the button it only does it for one random mod... and that's it... it should take a while but just does 1 mod! Yes i have mods not updated because bodyslider and bunch other mods i have aren't up to date and i've had to start manually checking each mod! This applies to SSE, Fallout, many other games.

- Latest NMM
- Windows 10
- Tried normal NMM and Trace.
- Clicked fix chrome button in nmm settings.
- Reset UI
- Restarted PC
- Enable / Disable exclamation mark for updates.
- Rescanned installed games
- Uninstalled, reinstalled NMM

When I go to reinstall and start it i always get this:
Unable to execute file: C:\Program Files\NMM\NexusClient.exe
CreateProcess failed: 740.
The requested operation requires elevation

^ Google says run it in admin, still doesn't resolve issue of no mod updates

This happens only once and every time i reinstall it and go to open it the first time??

I've noticed a bunch of these types of threads "per googling" that end up posted here! Yet i can never find a direct ANSWER to resolve the issue.

Advice please and thanks, this is the only time i've had issues with this, been using NMM since release, never had issues in the past, i've been using it for years! So either my PC messed up, or an Update lately messed up!

**Comment by Slorm** [comment]
I can confirm that there seems to be an issue with v87.2 not reading mod updates from Nexus. O/S is Win 10

I've since reinstalled v87.1 and that is working correctly

**Comment by DuskDweller** [comment]
There seems to be a bug in the most recent Pathoschild library:
Method not found: 'Pathoschild.Http.Client.IRequest Pathoschild.Http.Client.FluentClientExtensions.WithOptions(Pathoschild.Http.Client.IRequest, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>)'.'
It can't find its own stuff. I'll have a look at it but I can't give you an ETA.

**Comment by InsaneVRGamer** [comment]
> I can confirm that there seems to be an issue with v87.2 not reading mod updates from Nexus. O/S is Win 10
> 
> I've since reinstalled v87.1 and that is working correctly

Fantastic to know i'm not the only one!



> There seems to be a bug in the most recent Pathoschild library: Method not found: 'Pathoschild.Http.Client.IRequest Pathoschild.Http.Client.FluentClientExtensions.WithOptions(Pathoschild.Http.Client.IRequest, System.Nullable`1<Boolean>, System.Nullable`1)'.' It can't find its own stuff. I'll have a look at it but I can't give you an ETA.

Thanks be great to finally have NMM working against and hopefully detect mods, i have to go through hundreds manually checking updates!

**Comment by DuskDweller** [comment]
Fixed it in 0.87.3 .

**Comment by InsaneVRGamer** [comment]
> Fixed it in 0.87.3 .

Downloading it now, will try it out and update post in a moment not an hour or so later. I'm not one of those!

Still get code:740 after fresh install, but it's finally checking mods and giving me outdated stuff!!! YAY! thanks. Thanks for listening @DuskDweller to my thread and to previous persons post :) really appreciate it!

-
Tracing an Unhandled Exception:
Exception: 
Message: 
	Unable to cast object of type 'System.InvalidOperationException' to type 'Pathoschild.Http.Client.ApiException'.
Full Trace: 
	System.InvalidCastException: Unable to cast object of type 'System.InvalidOperationException' to type 'Pathoschild.Http.Client.ApiException'.
   at Nexus.Client.ModRepositories.NexusModsApiRepository.<>c__DisplayClass50_0.<ReactToAggregateException>b__0(Exception ex)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nexus.Client.ModRepositories.NexusModsApiRepository.ReactToAggregateException(AggregateException a)
   at Nexus.Client.ModRepositories.NexusModsApiRepository.GetFileListInfo(List`1 modFileList)
   at Nexus.Client.ModManagement.ModUpdateCheckTask.CheckForModListUpdate(List`1 modList, List`1 modsToCheck)
   at Nexus.Client.ModManagement.ModUpdateCheckTask.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)
    13 () 
        Aborted



^
I do get this now though, for fallout 4, wont happen with skyrim, probably a me thing that. No idea, but you've fixed updates, i'm glad!
