### ISSUE TITLE
i cant seem to get into my nexus mod manager 

### ISSUE THREAD

**Issue by payup112** [Nexus-Mods/Nexus-Mod-Manager#785]
I could open my nexus mod manager at first but it wouldn't update then i heard by deleting black_tree_gaming folder that would fix it.....it didn't now i cant even open it up and i restored it from my recycle bin but that didn't do anything either i just get a trace log error 

this is my trace log message at the bottom of the trace log please help!!

 Tracing an Unhandled Exception:
Exception: 
Message: 
	Could not find a part of the path 'C:\Users\james\AppData\Local\Temp\NexusModManager\crhw3j4q.bzs\--- Screenshots ---\EverythingWithDragonborn.jpg'.
Full Trace: 
	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\james\AppData\Local\Temp\NexusModManager\crhw3j4q.bzs\--- Screenshots ---\EverythingWithDragonborn.jpg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Nexus.Client.Util.Archive.GetFileContents(String p_strPath)
   at Nexus.Client.ModManagement.Scripting.XmlScript.ConditionStateManager.GetImage(String p_strPath)
   at Nexus.Client.ModManagement.Scripting.XmlScript.UI.OptionFormStep.lvwPlugins_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Realistic Water Two v1_11-41076-1-11.7z] Adding mod from archive.
Running Threads (1)
            19 () 
                Aborted

**Comment by squid-box** [comment]
It would be more useful with a full trace log. I think this was resolved back during 0.65.8 or something.

**Comment by payup112** [comment]
i can give my full trace log Trace file has been created: TraceLog20181231161906.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Morrowind.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Oblivion.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Skyrim: Supported
Determining Game Mode: (Requested Mode: skyrim) skyrim
Game Mode Factory Selected: Skyrim (Skyrim)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim (Skyrim)
    Installation Path: c:\program files (x86)\steam\steamapps\common\Skyrim
    Install Info Path: c:\Games\Nexus Mod Manager\Skyrim\Install Info
    Mod Path: c:\Games\Nexus Mod Manager\Skyrim\Mods
    Mod Cache Path: c:\Games\Nexus Mod Manager\Skyrim\Mods\cache
    Mod Download Cache: c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads
    Overwrite Path: c:\Games\Nexus Mod Manager\Skyrim\Install Info\overwrites
    Virtual Install Path: c:\Games\Nexus Mod Manager\Skyrim\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: Skyrim.CSharpScript.dll
                Initializing: Nexus.Client.Games.Skyrim.Scripting.CSharpScript.SkyrimCSharpScriptType
            Checking: Skyrim.XmlScript.dll
                Initializing: Nexus.Client.Games.Skyrim.Scripting.XmlScript.SkyrimXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: c:\Games\Nexus Mod Manager\Skyrim\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: c:\Games\Nexus Mod Manager\Skyrim\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: c:\program files (x86)\steam\steamapps\common\Skyrim\Data
                Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dawnguard.esm
                Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dragonborn.esm
                Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\HearthFires.esm
                Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Skyrim.esm
                Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Update.esm
            Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dawnguard.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dragonborn.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\HearthFires.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Skyrim.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Update.esm
                Registered.
        Found 5 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Skyrim.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Update.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dawnguard.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Skyrim\Data\HearthFires.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dragonborn.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: c:\program files (x86)\steam\steamapps\common\Skyrim\SkyrimLauncher.exe (IsNull=False)
    SKSE Command: c:\program files (x86)\steam\steamapps\common\Skyrim\skse_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command: C:\Program Files (x86)\LOOT\LOOT.exe (IsNull=False)
    Wrye Bash Command:  (IsNull=False)
    TES5Edit Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Loading Plugins into Plugin List: 5
    Loading: Skyrim.esm (c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Skyrim.esm) (False)
    Loading: Update.esm (c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Update.esm) (False)
    Loading: Dawnguard.esm (c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dawnguard.esm) (False)
    Loading: HearthFires.esm (c:\program files (x86)\steam\steamapps\common\Skyrim\Data\HearthFires.esm) (False)
    Loading: Dragonborn.esm (c:\program files (x86)\steam\steamapps\common\Skyrim\Data\Dragonborn.esm) (False)
Setting up listener on Nexus Mod Manager-SkyrimIpcServer/SkyrimListener at 2018-12-31 16:19:07
Adding mod: nxm://skyrim/mods/3863/files/1000172397?key=tklYXSsK7t6p0ZAsxod6Jw&expires=1546467542
Adding Mod to running instance of client: nxm://skyrim/mods/3863/files/1000172397?key=tklYXSsK7t6p0ZAsxod6Jw&expires=1546467542
[nxm://skyrim/mods/3863/files/1000172397?key=tklYXSsK7t6p0ZAsxod6Jw&expires=1546467542] Adding Mod to AddModQueue
[nxm://skyrim/mods/3863/files/1000172397?key=tklYXSsK7t6p0ZAsxod6Jw&expires=1546467542] Starting Add Mod Task.
Running Application.
[nxm://skyrim/mods/3863/files/1000172397?key=tklYXSsK7t6p0ZAsxod6Jw&expires=1546467542] Starting Add Mod Task.
[nxm://skyrim/mods/3863/files/1000172397?key=tklYXSsK7t6p0ZAsxod6Jw&expires=1546467542] Downloading Files.
[nxm://skyrim/mods/3863/files/1000172397?key=tklYXSsK7t6p0ZAsxod6Jw&expires=1546467542] Launching downloading of https://supporter-files.nexus-cdn.com/110/3863/SkyUI_5_1-3863-5-1.7z?md5=suf92VL3tiiBRiHsae6wLQ&expires=1546467551&user_id=19501949&rip=64.135.216.192.
[https://supporter-files.nexus-cdn.com/110/3863/SkyUI_5_1-3863-5-1.7z?md5=suf92VL3tiiBRiHsae6wLQ&expires=1546467551&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
[https://supporter-files.nexus-cdn.com/110/3863/SkyUI_5_1-3863-5-1.7z?md5=suf92VL3tiiBRiHsae6wLQ&expires=1546467551&user_id=19501949&rip=64.135.216.192] Downloading.
[c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\SkyUI_5_1-3863-5-1.7z] Adding mod from archive.
Adding Mod to running instance of client: nxm://skyrim/mods/11811/files/1000273589?key=nitqHOIKcWW6YySco-duLw&expires=1546467602
[nxm://skyrim/mods/11811/files/1000273589?key=nitqHOIKcWW6YySco-duLw&expires=1546467602] Adding Mod to AddModQueue
[nxm://skyrim/mods/11811/files/1000273589?key=nitqHOIKcWW6YySco-duLw&expires=1546467602] Starting Add Mod Task.
[nxm://skyrim/mods/11811/files/1000273589?key=nitqHOIKcWW6YySco-duLw&expires=1546467602] Starting Add Mod Task.
[nxm://skyrim/mods/11811/files/1000273589?key=nitqHOIKcWW6YySco-duLw&expires=1546467602] Downloading Files.
[nxm://skyrim/mods/11811/files/1000273589?key=nitqHOIKcWW6YySco-duLw&expires=1546467602] Launching downloading of https://supporter-files.nexus-cdn.com/110/11811/FNIS Behavior 7_4_5-11811-7-4-5.7z?md5=DNCeV-0ZJrA4lux2N_NmzQ&expires=1546467605&user_id=19501949&rip=64.135.216.192.
[https://supporter-files.nexus-cdn.com/110/11811/FNIS Behavior 7_4_5-11811-7-4-5.7z?md5=DNCeV-0ZJrA4lux2N_NmzQ&expires=1546467605&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
[https://supporter-files.nexus-cdn.com/110/11811/FNIS Behavior 7_4_5-11811-7-4-5.7z?md5=DNCeV-0ZJrA4lux2N_NmzQ&expires=1546467605&user_id=19501949&rip=64.135.216.192] Downloading.
[c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\FNIS Behavior 7_4_5-11811-7-4-5.7z] Adding mod from archive.
Configuring FNIS
    Configuring FNIS
        Adding Mod to running instance of client: nxm://skyrim/mods/8655/files/1000276682?key=7vw4DsCGZB0f_TF9QbXdYg&expires=1546467949
        [nxm://skyrim/mods/8655/files/1000276682?key=7vw4DsCGZB0f_TF9QbXdYg&expires=1546467949] Adding Mod to AddModQueue
        [nxm://skyrim/mods/8655/files/1000276682?key=7vw4DsCGZB0f_TF9QbXdYg&expires=1546467949] Starting Add Mod Task.
        [nxm://skyrim/mods/8655/files/1000276682?key=7vw4DsCGZB0f_TF9QbXdYg&expires=1546467949] Starting Add Mod Task.
        [nxm://skyrim/mods/8655/files/1000276682?key=7vw4DsCGZB0f_TF9QbXdYg&expires=1546467949] Downloading Files.
        [nxm://skyrim/mods/8655/files/1000276682?key=7vw4DsCGZB0f_TF9QbXdYg&expires=1546467949] Launching downloading of https://supporter-files.nexus-cdn.com/110/8655/SMIM 2-08-8655-2-08.7z?md5=cufpNXter0u0mLizUXG9oQ&expires=1546467951&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/8655/SMIM 2-08-8655-2-08.7z?md5=cufpNXter0u0mLizUXG9oQ&expires=1546467951&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/8655/SMIM 2-08-8655-2-08.7z?md5=cufpNXter0u0mLizUXG9oQ&expires=1546467951&user_id=19501949&rip=64.135.216.192] Downloading.
        Adding Mod to running instance of client: nxm://skyrim/mods/8655/files/1000276682?key=7vw4DsCGZB0f_TF9QbXdYg&expires=1546467949
        Adding Mod to running instance of client: nxm://skyrim/mods/141/files/1000281549?key=wT0JIvmMWjmGVAZXVqG-kQ&expires=1546468067
        [nxm://skyrim/mods/141/files/1000281549?key=wT0JIvmMWjmGVAZXVqG-kQ&expires=1546468067] Adding Mod to AddModQueue
        [nxm://skyrim/mods/141/files/1000281549?key=wT0JIvmMWjmGVAZXVqG-kQ&expires=1546468067] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000281549?key=wT0JIvmMWjmGVAZXVqG-kQ&expires=1546468067] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000281549?key=wT0JIvmMWjmGVAZXVqG-kQ&expires=1546468067] Downloading Files.
        [nxm://skyrim/mods/141/files/1000281549?key=wT0JIvmMWjmGVAZXVqG-kQ&expires=1546468067] Launching downloading of https://supporter-files.nexus-cdn.com/110/141/Dyndolod 3D trees-141-2-6.7z?md5=UMrYRLyZ4dK_7AGvXUCIuw&expires=1546468070&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/141/Dyndolod 3D trees-141-2-6.7z?md5=UMrYRLyZ4dK_7AGvXUCIuw&expires=1546468070&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/141/Dyndolod 3D trees-141-2-6.7z?md5=UMrYRLyZ4dK_7AGvXUCIuw&expires=1546468070&user_id=19501949&rip=64.135.216.192] Downloading.
        Adding Mod to running instance of client: nxm://skyrim/mods/141/files/1000266292?key=a07MVofvZtjn7AsESbzpQw&expires=1546468075
        [nxm://skyrim/mods/141/files/1000266292?key=a07MVofvZtjn7AsESbzpQw&expires=1546468075] Adding Mod to AddModQueue
        [nxm://skyrim/mods/141/files/1000266292?key=a07MVofvZtjn7AsESbzpQw&expires=1546468075] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000266292?key=a07MVofvZtjn7AsESbzpQw&expires=1546468075] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000266292?key=a07MVofvZtjn7AsESbzpQw&expires=1546468075] Downloading Files.
        [nxm://skyrim/mods/141/files/1000266292?key=a07MVofvZtjn7AsESbzpQw&expires=1546468075] Launching downloading of https://supporter-files.nexus-cdn.com/110/141/SFO  NO Grass  v2.6-141-2-6.7z?md5=7zZ0yfyb3b3AS16yiPQHJw&expires=1546468079&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/141/SFO  NO Grass  v2.6-141-2-6.7z?md5=7zZ0yfyb3b3AS16yiPQHJw&expires=1546468079&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/141/SFO  NO Grass  v2.6-141-2-6.7z?md5=7zZ0yfyb3b3AS16yiPQHJw&expires=1546468079&user_id=19501949&rip=64.135.216.192] Downloading.
        Adding Mod to running instance of client: nxm://skyrim/mods/141/files/1000254256?key=PtoqbV8z7IvWvc1-IsDywQ&expires=1546468088
        [nxm://skyrim/mods/141/files/1000254256?key=PtoqbV8z7IvWvc1-IsDywQ&expires=1546468088] Adding Mod to AddModQueue
        [nxm://skyrim/mods/141/files/1000254256?key=PtoqbV8z7IvWvc1-IsDywQ&expires=1546468088] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000254256?key=PtoqbV8z7IvWvc1-IsDywQ&expires=1546468088] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000254256?key=PtoqbV8z7IvWvc1-IsDywQ&expires=1546468088] Downloading Files.
        [nxm://skyrim/mods/141/files/1000254256?key=PtoqbV8z7IvWvc1-IsDywQ&expires=1546468088] Launching downloading of https://supporter-files.nexus-cdn.com/110/141/SFO Billboards for v2.5C-141-.7z?md5=7eZxGPqmsazEzPkwx966Kg&expires=1546468092&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/141/SFO Billboards for v2.5C-141-.7z?md5=7eZxGPqmsazEzPkwx966Kg&expires=1546468092&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/141/SFO Billboards for v2.5C-141-.7z?md5=7eZxGPqmsazEzPkwx966Kg&expires=1546468092&user_id=19501949&rip=64.135.216.192] Downloading.
        Adding Mod to running instance of client: nxm://skyrim/mods/141/files/1000282295?key=EktPmcIYBu3E-H6qizWs4g&expires=1546468097
        [nxm://skyrim/mods/141/files/1000282295?key=EktPmcIYBu3E-H6qizWs4g&expires=1546468097] Adding Mod to AddModQueue
        [nxm://skyrim/mods/141/files/1000282295?key=EktPmcIYBu3E-H6qizWs4g&expires=1546468097] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000282295?key=EktPmcIYBu3E-H6qizWs4g&expires=1546468097] Starting Add Mod Task.
        [nxm://skyrim/mods/141/files/1000282295?key=EktPmcIYBu3E-H6qizWs4g&expires=1546468097] Downloading Files.
        [nxm://skyrim/mods/141/files/1000282295?key=EktPmcIYBu3E-H6qizWs4g&expires=1546468097] Launching downloading of https://supporter-files.nexus-cdn.com/110/141/SFO billboards for v2.6-141-2-6.zip?md5=mH6kLOJrMlRNacD-DI5TgQ&expires=1546468100&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/141/SFO billboards for v2.6-141-2-6.zip?md5=mH6kLOJrMlRNacD-DI5TgQ&expires=1546468100&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/141/SFO billboards for v2.6-141-2-6.zip?md5=mH6kLOJrMlRNacD-DI5TgQ&expires=1546468100&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Dyndolod 3D trees-141-2-6.7z] Adding mod from archive.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\SFO Billboards for v2.5C-141-.7z] Adding mod from archive.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\SFO billboards for v2.6-141-2-6.zip] Adding mod from archive.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\SFO  NO Grass  v2.6-141-2-6.7z] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/60/files/1000283818?key=-bay0WVwrNHkISDv9jkTmQ&expires=1546468680
        [nxm://skyrim/mods/60/files/1000283818?key=-bay0WVwrNHkISDv9jkTmQ&expires=1546468680] Adding Mod to AddModQueue
        [nxm://skyrim/mods/60/files/1000283818?key=-bay0WVwrNHkISDv9jkTmQ&expires=1546468680] Starting Add Mod Task.
        [nxm://skyrim/mods/60/files/1000283818?key=-bay0WVwrNHkISDv9jkTmQ&expires=1546468680] Starting Add Mod Task.
        [nxm://skyrim/mods/60/files/1000283818?key=-bay0WVwrNHkISDv9jkTmQ&expires=1546468680] Downloading Files.
        [nxm://skyrim/mods/60/files/1000283818?key=-bay0WVwrNHkISDv9jkTmQ&expires=1546468680] Launching downloading of https://supporter-files.nexus-cdn.com/110/60/Enhanced Blood Textures 3_8 NMM-60-3-8.7z?md5=JMxhxmpEYQtI3bIuxGzt6A&expires=1546468686&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/60/Enhanced Blood Textures 3_8 NMM-60-3-8.7z?md5=JMxhxmpEYQtI3bIuxGzt6A&expires=1546468686&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/60/Enhanced Blood Textures 3_8 NMM-60-3-8.7z?md5=JMxhxmpEYQtI3bIuxGzt6A&expires=1546468686&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\SMIM 2-08-8655-2-08.7z] Adding mod from archive.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Enhanced Blood Textures 3_8 NMM-60-3-8.7z] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/4929/files/1000230662?key=Di0kZcsVnP376Ci3-6kgPg&expires=1546468951
        [nxm://skyrim/mods/4929/files/1000230662?key=Di0kZcsVnP376Ci3-6kgPg&expires=1546468951] Adding Mod to AddModQueue
        [nxm://skyrim/mods/4929/files/1000230662?key=Di0kZcsVnP376Ci3-6kgPg&expires=1546468951] Starting Add Mod Task.
        [nxm://skyrim/mods/4929/files/1000230662?key=Di0kZcsVnP376Ci3-6kgPg&expires=1546468951] Starting Add Mod Task.
        [nxm://skyrim/mods/4929/files/1000230662?key=Di0kZcsVnP376Ci3-6kgPg&expires=1546468951] Downloading Files.
        [nxm://skyrim/mods/4929/files/1000230662?key=Di0kZcsVnP376Ci3-6kgPg&expires=1546468951] Launching downloading of https://supporter-files.nexus-cdn.com/110/4929/A Quality World Map 9.0.1 - Vivid with Flat Roads-4929-9-0-1VF.zip?md5=EOIvhoDt5qTereaJFRhW5w&expires=1546468953&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/4929/A Quality World Map 9.0.1 - Vivid with Flat Roads-4929-9-0-1VF.zip?md5=EOIvhoDt5qTereaJFRhW5w&expires=1546468953&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/4929/A Quality World Map 9.0.1 - Vivid with Flat Roads-4929-9-0-1VF.zip?md5=EOIvhoDt5qTereaJFRhW5w&expires=1546468953&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\A Quality World Map 9.0.1 - Vivid with Flat Roads-4929-9-0-1VF.zip] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/601/files/1000268686?key=yaiWWcHgsoTAuqVj-Wh9yQ&expires=1546469053
        [nxm://skyrim/mods/601/files/1000268686?key=yaiWWcHgsoTAuqVj-Wh9yQ&expires=1546469053] Adding Mod to AddModQueue
        [nxm://skyrim/mods/601/files/1000268686?key=yaiWWcHgsoTAuqVj-Wh9yQ&expires=1546469053] Starting Add Mod Task.
        [nxm://skyrim/mods/601/files/1000268686?key=yaiWWcHgsoTAuqVj-Wh9yQ&expires=1546469053] Starting Add Mod Task.
        [nxm://skyrim/mods/601/files/1000268686?key=yaiWWcHgsoTAuqVj-Wh9yQ&expires=1546469053] Downloading Files.
        [nxm://skyrim/mods/601/files/1000268686?key=yaiWWcHgsoTAuqVj-Wh9yQ&expires=1546469053] Launching downloading of https://supporter-files.nexus-cdn.com/110/601/Plugin Files Only (esp)-601-1-9.zip?md5=4aOaAj26fKtJG2PN37DXFg&expires=1546469055&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/601/Plugin Files Only (esp)-601-1-9.zip?md5=4aOaAj26fKtJG2PN37DXFg&expires=1546469055&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/601/Plugin Files Only (esp)-601-1-9.zip?md5=4aOaAj26fKtJG2PN37DXFg&expires=1546469055&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Plugin Files Only (esp)-601-1-9.zip] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/26800/files/1000200791?key=QxH16bfYwDAGHt-7xe0OGQ&expires=1546469089
        [nxm://skyrim/mods/26800/files/1000200791?key=QxH16bfYwDAGHt-7xe0OGQ&expires=1546469089] Adding Mod to AddModQueue
        [nxm://skyrim/mods/26800/files/1000200791?key=QxH16bfYwDAGHt-7xe0OGQ&expires=1546469089] Starting Add Mod Task.
        [nxm://skyrim/mods/26800/files/1000200791?key=QxH16bfYwDAGHt-7xe0OGQ&expires=1546469089] Starting Add Mod Task.
        [nxm://skyrim/mods/26800/files/1000200791?key=QxH16bfYwDAGHt-7xe0OGQ&expires=1546469089] Downloading Files.
        [nxm://skyrim/mods/26800/files/1000200791?key=QxH16bfYwDAGHt-7xe0OGQ&expires=1546469089] Launching downloading of https://supporter-files.nexus-cdn.com/110/26800/XP32 Maximum Skeleton-26800-1-96.7z?md5=c7uDoHD1gbMOEzjBARTrRQ&expires=1546469108&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/26800/XP32 Maximum Skeleton-26800-1-96.7z?md5=c7uDoHD1gbMOEzjBARTrRQ&expires=1546469108&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/26800/XP32 Maximum Skeleton-26800-1-96.7z?md5=c7uDoHD1gbMOEzjBARTrRQ&expires=1546469108&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\XP32 Maximum Skeleton-26800-1-96.7z] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/53996/files/1000109251?key=pnehmBXFC1ywaUBD5Iuhhw&expires=1546469148
        [nxm://skyrim/mods/53996/files/1000109251?key=pnehmBXFC1ywaUBD5Iuhhw&expires=1546469148] Adding Mod to AddModQueue
        [nxm://skyrim/mods/53996/files/1000109251?key=pnehmBXFC1ywaUBD5Iuhhw&expires=1546469148] Starting Add Mod Task.
        [nxm://skyrim/mods/53996/files/1000109251?key=pnehmBXFC1ywaUBD5Iuhhw&expires=1546469148] Starting Add Mod Task.
        [nxm://skyrim/mods/53996/files/1000109251?key=pnehmBXFC1ywaUBD5Iuhhw&expires=1546469148] Downloading Files.
        [nxm://skyrim/mods/53996/files/1000109251?key=pnehmBXFC1ywaUBD5Iuhhw&expires=1546469148] Launching downloading of https://supporter-files.nexus-cdn.com/110/53996/HDT Physics Extensions-53996-14-28.7z?md5=N1TnNB4k9vgHhz8gGJmIYg&expires=1546469151&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/53996/HDT Physics Extensions-53996-14-28.7z?md5=N1TnNB4k9vgHhz8gGJmIYg&expires=1546469151&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/53996/HDT Physics Extensions-53996-14-28.7z?md5=N1TnNB4k9vgHhz8gGJmIYg&expires=1546469151&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\HDT Physics Extensions-53996-14-28.7z] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/2666/files/1000170527?key=WqBmLnUF2w03tQp6AMkCpQ&expires=1546471047
        [nxm://skyrim/mods/2666/files/1000170527?key=WqBmLnUF2w03tQp6AMkCpQ&expires=1546471047] Adding Mod to AddModQueue
        [nxm://skyrim/mods/2666/files/1000170527?key=WqBmLnUF2w03tQp6AMkCpQ&expires=1546471047] Starting Add Mod Task.
        [nxm://skyrim/mods/2666/files/1000170527?key=WqBmLnUF2w03tQp6AMkCpQ&expires=1546471047] Starting Add Mod Task.
        [nxm://skyrim/mods/2666/files/1000170527?key=WqBmLnUF2w03tQp6AMkCpQ&expires=1546471047] Downloading Files.
        [nxm://skyrim/mods/2666/files/1000170527?key=WqBmLnUF2w03tQp6AMkCpQ&expires=1546471047] Launching downloading of https://supporter-files.nexus-cdn.com/110/2666/Caliente's Beautiful Bodies Edition v3.4f-2666-3-4f.7z?md5=-QX3P-3ngAPSEVsKy5scFw&expires=1546471050&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/2666/Caliente's Beautiful Bodies Edition v3.4f-2666-3-4f.7z?md5=-QX3P-3ngAPSEVsKy5scFw&expires=1546471050&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/2666/Caliente's Beautiful Bodies Edition v3.4f-2666-3-4f.7z?md5=-QX3P-3ngAPSEVsKy5scFw&expires=1546471050&user_id=19501949&rip=64.135.216.192] Downloading.
        Adding Mod to running instance of client: nxm://skyrim/mods/6709/files/25994?key=q0vTBm_uuxJcESubmkPVxg&expires=1546471103
        [nxm://skyrim/mods/6709/files/25994?key=q0vTBm_uuxJcESubmkPVxg&expires=1546471103] Adding Mod to AddModQueue
        [nxm://skyrim/mods/6709/files/25994?key=q0vTBm_uuxJcESubmkPVxg&expires=1546471103] Starting Add Mod Task.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Caliente's Beautiful Bodies Edition v3.4f-2666-3-4f.7z] Adding mod from archive.
        [nxm://skyrim/mods/6709/files/25994?key=q0vTBm_uuxJcESubmkPVxg&expires=1546471103] Starting Add Mod Task.
        [nxm://skyrim/mods/6709/files/25994?key=q0vTBm_uuxJcESubmkPVxg&expires=1546471103] Downloading Files.
        [nxm://skyrim/mods/6709/files/25994?key=q0vTBm_uuxJcESubmkPVxg&expires=1546471103] Launching downloading of https://supporter-files.nexus-cdn.com/110/6709/UNP BASE Skinny body V1dot2-6709.7z?md5=Ro2HevYckYKeIFeW62M-KA&expires=1546471107&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/6709/UNP BASE Skinny body V1dot2-6709.7z?md5=Ro2HevYckYKeIFeW62M-KA&expires=1546471107&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/6709/UNP BASE Skinny body V1dot2-6709.7z?md5=Ro2HevYckYKeIFeW62M-KA&expires=1546471107&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\UNP BASE Skinny body V1dot2-6709.7z] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/72586/files/1000193545?key=Bj24PJJPxNq9mCrbqsfsRg&expires=1546471200
        [nxm://skyrim/mods/72586/files/1000193545?key=Bj24PJJPxNq9mCrbqsfsRg&expires=1546471200] Adding Mod to AddModQueue
        [nxm://skyrim/mods/72586/files/1000193545?key=Bj24PJJPxNq9mCrbqsfsRg&expires=1546471200] Starting Add Mod Task.
        [nxm://skyrim/mods/72586/files/1000193545?key=Bj24PJJPxNq9mCrbqsfsRg&expires=1546471200] Starting Add Mod Task.
        [nxm://skyrim/mods/72586/files/1000193545?key=Bj24PJJPxNq9mCrbqsfsRg&expires=1546471200] Downloading Files.
        [nxm://skyrim/mods/72586/files/1000193545?key=Bj24PJJPxNq9mCrbqsfsRg&expires=1546471200] Launching downloading of https://supporter-files.nexus-cdn.com/110/72586/Pride of Valhalla CBBE - Niflheim-72586-v1-3.rar?md5=thbuWUSIB0CYD5KBqhQDxQ&expires=1546471206&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/72586/Pride of Valhalla CBBE - Niflheim-72586-v1-3.rar?md5=thbuWUSIB0CYD5KBqhQDxQ&expires=1546471206&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/72586/Pride of Valhalla CBBE - Niflheim-72586-v1-3.rar?md5=thbuWUSIB0CYD5KBqhQDxQ&expires=1546471206&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Pride of Valhalla CBBE - Niflheim-72586-v1-3.rar] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/93650/files/1000282899?key=ohmv7wIY9JD7E_9bweDSQw&expires=1546471316
        [nxm://skyrim/mods/93650/files/1000282899?key=ohmv7wIY9JD7E_9bweDSQw&expires=1546471316] Adding Mod to AddModQueue
        [nxm://skyrim/mods/93650/files/1000282899?key=ohmv7wIY9JD7E_9bweDSQw&expires=1546471316] Starting Add Mod Task.
        [nxm://skyrim/mods/93650/files/1000282899?key=ohmv7wIY9JD7E_9bweDSQw&expires=1546471316] Starting Add Mod Task.
        [nxm://skyrim/mods/93650/files/1000282899?key=ohmv7wIY9JD7E_9bweDSQw&expires=1546471316] Downloading Files.
        [nxm://skyrim/mods/93650/files/1000282899?key=ohmv7wIY9JD7E_9bweDSQw&expires=1546471316] Launching downloading of https://supporter-files.nexus-cdn.com/110/93650/All in one nude 4k-93650-3-0.7z?md5=pEejy9vWWVK-KZmxqG7XwA&expires=1546471319&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/93650/All in one nude 4k-93650-3-0.7z?md5=pEejy9vWWVK-KZmxqG7XwA&expires=1546471319&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/93650/All in one nude 4k-93650-3-0.7z?md5=pEejy9vWWVK-KZmxqG7XwA&expires=1546471319&user_id=19501949&rip=64.135.216.192] Downloading.
        Adding Mod to running instance of client: nxm://skyrim/mods/71214/files/1000271742?key=VRUf89ELnYYN-7JoGdHpsQ&expires=1546471462
        [nxm://skyrim/mods/71214/files/1000271742?key=VRUf89ELnYYN-7JoGdHpsQ&expires=1546471462] Adding Mod to AddModQueue
        [nxm://skyrim/mods/71214/files/1000271742?key=VRUf89ELnYYN-7JoGdHpsQ&expires=1546471462] Starting Add Mod Task.
        [nxm://skyrim/mods/71214/files/1000271742?key=VRUf89ELnYYN-7JoGdHpsQ&expires=1546471462] Starting Add Mod Task.
        [nxm://skyrim/mods/71214/files/1000271742?key=VRUf89ELnYYN-7JoGdHpsQ&expires=1546471462] Downloading Files.
        [nxm://skyrim/mods/71214/files/1000271742?key=VRUf89ELnYYN-7JoGdHpsQ&expires=1546471462] Launching downloading of https://supporter-files.nexus-cdn.com/110/71214/Unofficial Skyrim Legendary Edition Patch-71214-3-0-13a.7z?md5=knlNQ9DDbDrHckb_l2K9yg&expires=1546471467&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/71214/Unofficial Skyrim Legendary Edition Patch-71214-3-0-13a.7z?md5=knlNQ9DDbDrHckb_l2K9yg&expires=1546471467&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/71214/Unofficial Skyrim Legendary Edition Patch-71214-3-0-13a.7z?md5=knlNQ9DDbDrHckb_l2K9yg&expires=1546471467&user_id=19501949&rip=64.135.216.192] Downloading.
        Adding Mod to running instance of client: nxm://skyrim/mods/54527/files/1000249074?key=nR1yzPOyvEt25__so-zpIQ&expires=1546471740
        [nxm://skyrim/mods/54527/files/1000249074?key=nR1yzPOyvEt25__so-zpIQ&expires=1546471740] Adding Mod to AddModQueue
        [nxm://skyrim/mods/54527/files/1000249074?key=nR1yzPOyvEt25__so-zpIQ&expires=1546471740] Starting Add Mod Task.
        [nxm://skyrim/mods/54527/files/1000249074?key=nR1yzPOyvEt25__so-zpIQ&expires=1546471740] Starting Add Mod Task.
        [nxm://skyrim/mods/54527/files/1000249074?key=nR1yzPOyvEt25__so-zpIQ&expires=1546471740] Downloading Files.
        [nxm://skyrim/mods/54527/files/1000249074?key=nR1yzPOyvEt25__so-zpIQ&expires=1546471740] Launching downloading of https://supporter-files.nexus-cdn.com/110/54527/Sofia Follower v.2.51 (BSA)-54527-v-2-51.rar?md5=k6mMDSOZojO1n4iyfrGC-Q&expires=1546471743&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/54527/Sofia Follower v.2.51 (BSA)-54527-v-2-51.rar?md5=k6mMDSOZojO1n4iyfrGC-Q&expires=1546471743&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/54527/Sofia Follower v.2.51 (BSA)-54527-v-2-51.rar?md5=k6mMDSOZojO1n4iyfrGC-Q&expires=1546471743&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Unofficial Skyrim Legendary Edition Patch-71214-3-0-13a.7z] Adding mod from archive.
        Adding Mod to running instance of client: nxm://skyrim/mods/61348/files/1000285843?key=35TKzaEHgLO1uouafHODYA&expires=1546471776
        [nxm://skyrim/mods/61348/files/1000285843?key=35TKzaEHgLO1uouafHODYA&expires=1546471776] Adding Mod to AddModQueue
        [nxm://skyrim/mods/61348/files/1000285843?key=35TKzaEHgLO1uouafHODYA&expires=1546471776] Starting Add Mod Task.
        [nxm://skyrim/mods/61348/files/1000285843?key=35TKzaEHgLO1uouafHODYA&expires=1546471776] Starting Add Mod Task.
        [nxm://skyrim/mods/61348/files/1000285843?key=35TKzaEHgLO1uouafHODYA&expires=1546471776] Downloading Files.
        [nxm://skyrim/mods/61348/files/1000285843?key=35TKzaEHgLO1uouafHODYA&expires=1546471776] Launching downloading of https://supporter-files.nexus-cdn.com/110/61348/Sofia Customizer Redux - CBBE - 6.4-61348-6-4-1541957697.7z?md5=VBrkb6UPSzgYgFzbmXxC3Q&expires=1546471926&user_id=19501949&rip=64.135.216.192.
        [https://supporter-files.nexus-cdn.com/110/61348/Sofia Customizer Redux - CBBE - 6.4-61348-6-4-1541957697.7z?md5=VBrkb6UPSzgYgFzbmXxC3Q&expires=1546471926&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
        [https://supporter-files.nexus-cdn.com/110/61348/Sofia Customizer Redux - CBBE - 6.4-61348-6-4-1541957697.7z?md5=VBrkb6UPSzgYgFzbmXxC3Q&expires=1546471926&user_id=19501949&rip=64.135.216.192] Downloading.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Sofia Follower v.2.51 (BSA)-54527-v-2-51.rar] Adding mod from archive.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\All in one nude 4k-93650-3-0.7z] Adding mod from archive.
        Adding Mod to running instance of client: file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL.7z
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL.7z] Starting Add Mod Task.
        Adding Mod to running instance of client: file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL.7z
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL.7z] Starting Add Mod Task.
        [c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Sofia Customizer Redux - CBBE - 6.4-61348-6-4-1541957697.7z] Adding mod from archive.
        Adding Mod to running instance of client: file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL-1.7z
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL-1.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL-1.7z] Starting Add Mod Task.
        Adding Mod to running instance of client: file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL-1.7z
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL-1.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/AppData/Local/Temp/SexLabFramework_v162_FULL-1.7z] Starting Add Mod Task.
        [file:///C:/Users/james/Downloads/SexLabFramework_v162_FULL.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/Downloads/SexLabFramework_v162_FULL.7z] Starting Add Mod Task.
        [C:\Users\james\Downloads\SexLabFramework_v162_FULL.7z] Adding mod from archive.
        [file:///C:/Users/james/Downloads/Selina Vampire Follower - 7B.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/Downloads/Selina Vampire Follower - 7B.7z] Starting Add Mod Task.
        [file:///C:/Users/james/Downloads/Selina Vampire Follower - 7B.7z] Starting Add Mod Task.
        [C:\Users\james\Downloads\Selina Vampire Follower - 7B.7z] Adding mod from archive.
        [file:///C:/Users/james/Downloads/SexLabMatchMaker.Rev7.zip] Adding Mod to AddModQueue
        [file:///C:/Users/james/Downloads/SexLabMatchMaker.Rev7.zip] Starting Add Mod Task.
        [C:\Users\james\Downloads\SexLabMatchMaker.Rev7.zip] Adding mod from archive.
        [file:///C:/Users/james/Downloads/SOS - Schlongs of Skyrim - 3.00.004.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/Downloads/SOS - Schlongs of Skyrim - 3.00.004.7z] Starting Add Mod Task.
        [C:\Users\james\Downloads\SOS - Schlongs of Skyrim - 3.00.004.7z] Adding mod from archive.
        [file:///C:/Users/james/Downloads/SOS - Schlongs of Skyrim - LightSE.7z] Adding Mod to AddModQueue
        [file:///C:/Users/james/Downloads/SOS - Schlongs of Skyrim - LightSE.7z] Starting Add Mod Task.
        [C:\Users\james\Downloads\SOS - Schlongs of Skyrim - LightSE.7z] Adding mod from archive.
        Creating C# Script Sandbox...
    ApplicationBase: C:\Program Files\Nexus Mod Manager
    PrivateBinPath: C:\Program Files\Nexus Mod Manager\GameModes;C:\Program Files\Nexus Mod Manager\ScriptTypes
Adding Mod to running instance of client: nxm://skyrim/mods/41076/files/1000081546?key=ypmxSbfAB59ljrf2qQdNkA&expires=1546473523
[nxm://skyrim/mods/41076/files/1000081546?key=ypmxSbfAB59ljrf2qQdNkA&expires=1546473523] Adding Mod to AddModQueue
[nxm://skyrim/mods/41076/files/1000081546?key=ypmxSbfAB59ljrf2qQdNkA&expires=1546473523] Starting Add Mod Task.
[nxm://skyrim/mods/41076/files/1000081546?key=ypmxSbfAB59ljrf2qQdNkA&expires=1546473523] Starting Add Mod Task.
[nxm://skyrim/mods/41076/files/1000081546?key=ypmxSbfAB59ljrf2qQdNkA&expires=1546473523] Downloading Files.
[nxm://skyrim/mods/41076/files/1000081546?key=ypmxSbfAB59ljrf2qQdNkA&expires=1546473523] Launching downloading of https://supporter-files.nexus-cdn.com/110/41076/Realistic Water Two v1_11-41076-1-11.7z?md5=TlhBHgpB5OFsnPkyRe_8zA&expires=1546473526&user_id=19501949&rip=64.135.216.192.
[https://supporter-files.nexus-cdn.com/110/41076/Realistic Water Two v1_11-41076-1-11.7z?md5=TlhBHgpB5OFsnPkyRe_8zA&expires=1546473526&user_id=19501949&rip=64.135.216.192] Retreiving metadata.
[https://supporter-files.nexus-cdn.com/110/41076/Realistic Water Two v1_11-41076-1-11.7z?md5=TlhBHgpB5OFsnPkyRe_8zA&expires=1546473526&user_id=19501949&rip=64.135.216.192] Downloading.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Could not find a part of the path 'C:\Users\james\AppData\Local\Temp\NexusModManager\crhw3j4q.bzs\--- Screenshots ---\EverythingWithDragonborn.jpg'.
Full Trace: 
	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\james\AppData\Local\Temp\NexusModManager\crhw3j4q.bzs\--- Screenshots ---\EverythingWithDragonborn.jpg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Nexus.Client.Util.Archive.GetFileContents(String p_strPath)
   at Nexus.Client.ModManagement.Scripting.XmlScript.ConditionStateManager.GetImage(String p_strPath)
   at Nexus.Client.ModManagement.Scripting.XmlScript.UI.OptionFormStep.lvwPlugins_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[c:\Games\Nexus Mod Manager\Skyrim\Mods\downloads\Realistic Water Two v1_11-41076-1-11.7z] Adding mod from archive.
Running Threads (1)
            19 () 
                Aborted

**Comment by squid-box** [comment]
So I was correct, this has been fixed already. You can find the new releases [here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases).

Note that anything below 0.70 will not be able to log into Nexus anymore, due to an API upgrade.

**Comment by payup112** [comment]
well im trying to download the new nexus mod manager and im still getting the trace log error

**Comment by DrkMako** [comment]
i resolved this issue by uninstalling NMM and keeping the configs as is. reinstalled and its functioning fine now
just make sure you select to keep things when you uninstall 
after that install new one and it works fine no errors

**Comment by payup112** [comment]
Thanks a lot  it works now
