### ISSUE TITLE
0.70.5 crash at startup

### ISSUE THREAD

**Issue by Flatpackhamster** [Nexus-Mods/Nexus-Mod-Manager#789]
**Describe the bug** 

I've upgraded to the latest NMM community version from 0.65.2 (I think - whichever the last Nexusmods one was) and I now get a crash from NMM as soon as it starts up.  I'm using NMM to mod Skyrim and Skyrim Special Edition, but I'm not really using SSE and it's only got a few mods in.  

Any advice on a solution is very welcome.

**Environment**

Windows 7 64-Bit, NMM 0.70.5.0, About 200 mods.

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
Tracing an Unhandled Exception:
        Exception: 
Message: 
	Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Full Trace: 
	System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Pathoschild.FluentNexus.NexusClient.GetDefaultUserAgent(String appName, String appVersion)
   at Pathoschild.FluentNexus.NexusClient..ctor(String apiKey, String appName, String appVersion, String baseUrl)
   at Nexus.Client.ModRepositories.ApiCallManager.UpdateNexusClient()
   at Nexus.Client.ModRepositories.ApiCallManager.Instance(IEnvironmentInfo environmentInfo)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by DuskDweller** [comment]
For any of you having the "unable to load DLL" issue, try downloading the Visual C++ redist and install it, this should fix it.
Please report back in any case:
https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by sabinoplane** [comment]
I already have Visual C++ redist installed and in fact it doesn't let me install it for that reason (says its already in the computer) however the crash still happens, any other fixes?

EDIT: got it to work somehow by reverting to previous version then coming back, problem comes when authorizing it to do the API key thingy or whatever it's called, i authorize it and then it tells me its missing a dll (I dont remember the name and i cant trigger this again) after it it just doesnt log in and when i try to restart it, bam, the unable to load DLL error.

**Comment by Flatpackhamster** [comment]
Hello,

I've uninstalled and reinstalled the C++ redist in the link above, restarted the PC, and I still get the same crash.

[TraceLog20190518125417.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3194026/TraceLog20190518125417.txt)


Tracelog:
-----------


Trace file has been created: TraceLog20190518125557.txt
Mod Manager Version: 0.70.5.0
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Skyrim: Supported
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) Skyrim
Game Mode Factory Selected: Skyrim (Skyrim)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim (Skyrim)
    Installation Path: E:\Steam\steamapps\common\Skyrim
    Install Info Path: E:\Games\Nexus Mod Manager\Skyrim\Install Info
    Mod Path: E:\Games\Nexus Mod Manager\Skyrim\Mods
    Mod Cache Path: E:\Games\Nexus Mod Manager\Skyrim\Mods\cache
    Mod Download Cache: E:\Games\Nexus Mod Manager\Skyrim\Mods\downloads
    Overwrite Path: E:\Games\Nexus Mod Manager\Skyrim\Install Info\overwrites
    Virtual Install Path: E:\Games\Nexus Mod Manager\Skyrim\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
    
    Tracing an Unhandled Exception:
    Running Threads (1)
    3 () 
        Aborted
        Exception: 
Message: 
	Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Full Trace: 
	System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Pathoschild.FluentNexus.NexusClient.GetDefaultUserAgent(String appName, String appVersion)
   at Pathoschild.FluentNexus.NexusClient..ctor(String apiKey, String appName, String appVersion, String baseUrl)
   at Nexus.Client.ModRepositories.ApiCallManager.UpdateNexusClient()
   at Nexus.Client.ModRepositories.ApiCallManager.Instance(IEnvironmentInfo environmentInfo)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by JanoTheCarp** [comment]
Exactly the same problem here... Just wanna leave a tactical dot (.)

Trying to reinstall Visual C + + 2015
- x86 version reinstall succeed
- but x64 version reinstall not succeed
   - cannot install because the version already installed
   - trying to uninstall with every method (manually, default, and forced with application)
   - only can be repaired
   - still not working

Idk what to do next... notify me when somebody figured out

Initializing Mod Repository...
    
    Tracing an Unhandled Exception:
    Running Threads (1)
    3 () 
        Aborted
        Exception: 
Message: 
	Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Full Trace: 
	System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Pathoschild.FluentNexus.NexusClient.GetDefaultUserAgent(String appName, String appVersion)
   at Pathoschild.FluentNexus.NexusClient..ctor(String apiKey, String appName, String appVersion, String baseUrl)
   at Nexus.Client.ModRepositories.ApiCallManager.UpdateNexusClient()
   at Nexus.Client.ModRepositories.ApiCallManager.Instance(IEnvironmentInfo environmentInfo)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by squid-box** [comment]
@Flatpackhamster & Co: Try installing [0.70.7](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and this message should no longer occur.
